# Generated by Django 3.2.5 on 2021-08-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210802_0228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
