# Generated by Django 3.2.5 on 2021-08-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_paycheck_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='total',
        ),
    ]
